name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Package Cloudformation artifacts (Lambda code)
        run: aws cloudformation package --template-file cfn_test.yml --s3-bucket ${{ secrets.AWS_CODE_BUCKET }} --output-template-file cfn_test_packaged.yml
    
      - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: test-lambda-stack
          template: cfn_test_packaged.yml
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: 1
          #role-arn:

      - name: Clean up artifacts
        run: rm -f cfn_test_packaged.yml
  
